name: Build and Deploy Local Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # 수동 실행

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: 저장소 코드 체크아웃 (Checkout Code)
        uses: actions/checkout@v4

      - name: 기존 컨테이너 중지 및 제거 (Stop and Remove old container)
        run: |
          $container = docker ps -a -q -f name=mlops-ai
          if ($container) {
              Write-Host "Removing existing container..."
              docker rm -f mlops-ai
          } else {
              Write-Host "Container does not exist, skipping removal."
          }
        continue-on-error: true

      - name: Docker 이미지 로컬 빌드 (Build Docker Image locally)
        run: |
          Write-Host "Building Docker image..."
          docker build -t mlops-ai-image-detector:latest .

      - name: 로컬 서버로 실행 (Deploy and Run Container)
        run: |
          Write-Host "Starting new container..."
          docker run -d --name mlops-ai -p 8000:8000 mlops-ai-image-detector:latest
