name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: 저장소 코드 체크아웃 (Checkout Code)
        uses: actions/checkout@v4

      - name: Docker Hub 로그인 (Login to Docker Hub)
        shell: cmd
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker 이미지 빌드 및 푸시 (Build and Push)
        shell: cmd
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mlops-ai-image-detector:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/mlops-ai-image-detector:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-ai-image-detector:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-ai-image-detector:${{ github.sha }}

      - name: 기존 컨테이너 중지 및 제거 (Stop and Remove old container)
        shell: cmd
        run: docker rm -f mlops-ai 2>nul & exit /b 0

      - name: 최신 이미지 Pull 및 컨테이너 실행 (Deploy and Run)
        shell: cmd
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mlops-ai-image-detector:latest
          docker run -d --name mlops-ai -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/mlops-ai-image-detector:latest
